[env:lilygo_t5_s3_pro]
extends = esp32_common
board = esp32s3devkitc1
build_flags =
  ${common.build_flags}
  ; LilyGO T5 S3 Pro (H752-01) board support
  -DBOARD_TYPE_LILYGO_T5_S3_PRO
  ; Setup display format and model via build flags (7.5" display)
  -DCONFIG_EPD_DISPLAY_TYPE_ED075TC1
  -DCONFIG_EPD_BOARD_REVISION_LILYGO_T5_S3_PRO
  ; setup the pins for the SDCard
  -DSD_CARD_PIN_NUM_MISO=GPIO_NUM_21
  -DSD_CARD_PIN_NUM_MOSI=GPIO_NUM_12
  -DSD_CARD_PIN_NUM_CLK=GPIO_NUM_14
  -DSD_CARD_PIN_NUM_CS=GPIO_NUM_10
  ; battery voltage divider connected to GPIO 11
  -DBATTERY_ADC_CHANNEL=ADC1_CHANNEL_0
  ; Touch configuration
  -D USE_L58_TOUCH
  -D CONFIG_TOUCH_SDA=39
  -D CONFIG_TOUCH_SDL=40
  -D CONFIG_TOUCH_INT=3
  -D CONFIG_I2C_MASTER_FREQUENCY=50000
  -D CONFIG_FT6X36_DEBUG=0
